import { Deal, Category } from "@/types";

const now = new Date();

const addHours = (date: Date, hours: number) =>
  new Date(date.getTime() + hours * 60 * 60 * 1000);

const addDays = (date: Date, days: number) =>
  new Date(date.getTime() + days * 24 * 60 * 60 * 1000);

export const todayDeals: Deal[] = [
  {
    id: "1",
    brand: "Nike",
    logo: "🏃",
    title: "Yaz Koleksiyonu %40 İndirim",
    discount: 40,
    originalPrice: 2499,
    salePrice: 1499,
    endsAt: addHours(now, 18),
    startsAt: addHours(now, -2),
    category: "Spor",
    imageUrl: "",
    badge: "hot",
  },
  {
    id: "2",
    brand: "Zara",
    logo: "👗",
    title: "Sezon Sonu Büyük İndirim",
    discount: 50,
    originalPrice: 1800,
    salePrice: 900,
    endsAt: addHours(now, 24),
    startsAt: addHours(now, -1),
    category: "Moda",
    imageUrl: "",
    badge: "new",
  },
  {
    id: "3",
    brand: "Teknosa",
    logo: "📱",
    title: "Elektronik Ürünlerde %30 İndirim",
    discount: 30,
    originalPrice: 15000,
    salePrice: 10500,
    endsAt: addHours(now, 12),
    startsAt: addHours(now, -3),
    category: "Elektronik",
    imageUrl: "",
  },
  {
    id: "4",
    brand: "Boyner",
    logo: "🛍️",
    title: "2 Al 1 Öde Kampanyası",
    discount: 50,
    originalPrice: 3200,
    salePrice: 1600,
    endsAt: addHours(now, 36),
    startsAt: addHours(now, -5),
    category: "Moda",
    imageUrl: "",
  },
  {
    id: "5",
    brand: "MediaMarkt",
    logo: "🖥️",
    title: "Laptop Fırsatları",
    discount: 25,
    originalPrice: 32000,
    salePrice: 24000,
    endsAt: addHours(now, 10),
    startsAt: addHours(now, -1),
    category: "Elektronik",
    imageUrl: "",
  },
  {
    id: "6",
    brand: "H&M",
    logo: "👔",
    title: "Erkek Giyimde %35 İndirim",
    discount: 35,
    originalPrice: 1200,
    salePrice: 780,
    endsAt: addHours(now, 20),
    startsAt: addHours(now, -4),
    category: "Moda",
    imageUrl: "",
    badge: "new",
  },
];

export const upcomingDeals: Deal[] = [
  {
    id: "7",
    brand: "Apple",
    logo: "🍎",
    title: "Back to School Kampanyası",
    discount: 15,
    originalPrice: 45000,
    salePrice: 38250,
    startsAt: addHours(now, 2),
    endsAt: addDays(now, 3),
    category: "Elektronik",
    imageUrl: "",
  },
  {
    id: "8",
    brand: "LC Waikiki",
    logo: "👕",
    title: "Okul Sezonu İndirimi",
    discount: 45,
    originalPrice: 800,
    salePrice: 440,
    startsAt: addHours(now, 5),
    endsAt: addDays(now, 7),
    category: "Moda",
    imageUrl: "",
  },
  {
    id: "9",
    brand: "Adidas",
    logo: "⚽",
    title: "Yeni Sezon Koleksiyonu",
    discount: 20,
    originalPrice: 3500,
    salePrice: 2800,
    startsAt: addHours(now, 8),
    endsAt: addDays(now, 5),
    category: "Spor",
    imageUrl: "",
  },
  {
    id: "10",
    brand: "Samsung",
    logo: "📺",
    title: "TV & Beyaz Eşya Fırsatları",
    discount: 35,
    originalPrice: 28000,
    salePrice: 18200,
    startsAt: addDays(now, 1),
    endsAt: addDays(now, 4),
    category: "Elektronik",
    imageUrl: "",
  },
];

export const lastHoursDeals: Deal[] = [
  {
    id: "11",
    brand: "Mango",
    logo: "🌸",
    title: "Son Saatler: %60 İndirim",
    discount: 60,
    originalPrice: 2200,
    salePrice: 880,
    endsAt: addHours(now, 3),
    startsAt: addHours(now, -20),
    category: "Moda",
    imageUrl: "",
    badge: "last",
  },
  {
    id: "12",
    brand: "Dyson",
    logo: "🌀",
    title: "Süpürge & Saç Bakım Fırsatı",
    discount: 30,
    originalPrice: 12000,
    salePrice: 8400,
    endsAt: addHours(now, 2),
    startsAt: addHours(now, -22),
    category: "Ev & Yaşam",
    imageUrl: "",
    badge: "last",
  },
  {
    id: "13",
    brand: "Sephora",
    logo: "💄",
    title: "Kozmetik Kampanyası Bitiyor",
    discount: 40,
    originalPrice: 950,
    salePrice: 570,
    endsAt: addHours(now, 1),
    startsAt: addHours(now, -23),
    category: "Güzellik",
    imageUrl: "",
    badge: "last",
  },
  {
    id: "14",
    brand: "Koton",
    logo: "🎀",
    title: "Kadın Giyim Son Fırsat",
    discount: 55,
    originalPrice: 1500,
    salePrice: 675,
    endsAt: addHours(now, 4),
    startsAt: addHours(now, -20),
    category: "Moda",
    imageUrl: "",
    badge: "last",
  },
];

export const categories: Category[] = [
  { id: "1", name: "Moda", icon: "👗", dealCount: 48, slug: "moda" },
  { id: "2", name: "Elektronik", icon: "📱", dealCount: 32, slug: "elektronik" },
  { id: "3", name: "Spor", icon: "⚽", dealCount: 21, slug: "spor" },
  { id: "4", name: "Ev & Yaşam", icon: "🏠", dealCount: 19, slug: "ev-yasam" },
  { id: "5", name: "Güzellik", icon: "💄", dealCount: 27, slug: "guzellik" },
  { id: "6", name: "Kitap & Kırtasiye", icon: "📚", dealCount: 14, slug: "kitap" },
  { id: "7", name: "Oyun & Hobi", icon: "🎮", dealCount: 11, slug: "oyun-hobi" },
  { id: "8", name: "Seyahat", icon: "✈️", dealCount: 9, slug: "seyahat" },
];
